array 


In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

array gepeng

In [11]:
list1 = ["ikan", "kucing", "beruang"]
list1 = np.array(list1)
print(list1)

print(list1.shape)
print("ini adalah array", list1.ndim, "D")

['ikan' 'kucing' 'beruang']
(3,)
ini adalah array 1 D


array papan

In [28]:
array_2d = np.array(([10,20,30], 
                     [40,50,60], 
                     [70,80,90]))
print(array_2d)

print(array_2d.shape)
print("ini adalah array", array_2d.ndim, "D" )
print(array_2d[0,2])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
ini adalah array 2 D
30


In [ ]:
array_2d_string = np.array(
    [
        ["apple", "banana", "cherry"],
        ["dog", "elephant", "fox"],
        ["grape", "honey", "ice"]
    ]
)
print(array_2d_string)
print(array_2d_string,[1,2])


[['apple' 'banana' 'cherry']
 ['dog' 'elephant' 'fox']
 ['grape' 'honey' 'ice']]
[['apple' 'banana' 'cherry']
 ['dog' 'elephant' 'fox']
 ['grape' 'honey' 'ice']] [1, 2]


menambahkan data

In [19]:
#array 1D

ar_id=np.array([10,20,30])
print(ar_id)

[10 20 30]


In [23]:
ar_id=np.append(ar_id, 11)
print(ar_id)

[10 20 30 11]


In [37]:
#array 2D
array_2d = ([10,20,30], 
            [40,50,60], 
            [70,80,90])

array_2d = np.append(array_2d, [[100,110,120]], axis=0)
print(array_2d)

array_2d = np.append(array_2d, 
                    [[130, 140, 150]], axis=0)
print(array_2d)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]
 [130 140 150]]


In [38]:
ar_id = np.delete(ar_id, 0)
print(ar_id)

[20 30 11]


In [45]:
#array 2D
array_2d = ([10,20,30], 
            [40,50,60], 
            [70,80,90])

array_2d = np.append(array_2d, [[100,110,120]], axis=0)
print(array_2d)

array_2d = np.append(array_2d, 
                    [[130, 140, 150]], axis=0)
print(array_2d)

array_2d = np.delete(array_2d, 0, axis=0)
print(array_2d)
array_2d = np.delete(array_2d, 1, axis=0)
print(array_2d)

maximun = np.max(array_2d)
minimun = np.min(array_2d)

print(maximun)
print(minimun)

mengurutkan =np.sort(array_2d, axis=0)
print(mengurutkan)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]
 [130 140 150]]
[[ 40  50  60]
 [ 70  80  90]
 [100 110 120]
 [130 140 150]]
[[ 40  50  60]
 [100 110 120]
 [130 140 150]]
150
40
[[ 40  50  60]
 [100 110 120]
 [130 140 150]]
